name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [ main ]
    
jobs:
  # Build the dockerfile
  Docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push dev
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/nirmalsunny/demo-golang-image:latest
